
services:
  # 1. VeritabanÄ± (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: ticketing_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ticketing_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketing-net

  # 2. VeritabanÄ± YÃ¶netim Paneli (Adminer) - TarayÄ±cÄ±dan DB gÃ¶rmek iÃ§in
  adminer:
    image: adminer
    container_name: ticketing_db_gui
    ports:
      - "8080:8080"
    networks:
      - ticketing-net

  # 3. Mesaj KuyruÄŸu (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ticketing_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ticketing-net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 4. Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ticketing_backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/usr/src/app
      # ðŸ‘‡ Ä°ÅžTE BU SATIRI EKLE (Aynen kopyala):
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/ticketing_db?schema=public
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - ticketing-net
    command: npm run start:dev

  # 5. Frontend (Next.js)
# ... (DiÄŸerleri aynÄ±)

  # 5. Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ticketing_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # DNS AYARI EKLENDÄ°: Ä°nternete Ã§Ä±kabilmesi iÃ§in
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - ticketing-net
    command: npm run dev

networks:
  ticketing-net:
    driver: bridge

volumes:
  postgres_data: